DROP TABLE Player_Team_Contract CASCADE CONSTRAINT;
DROP TABLE Coach_Team_Contract CASCADE CONSTRAINT;
DROP TABLE Player_PlaysRole_in_Match CASCADE CONSTRAINT;
DROP TABLE Player_Scores_in_Match CASCADE CONSTRAINT;
DROP TABLE Team_Wins_Championship CASCADE CONSTRAINT;
DROP TABLE Team_Participates_in_Match CASCADE CONSTRAINT;
DROP TABLE Sponsor_Sponsors_Match CASCADE CONSTRAINT;
DROP TABLE Team;
DROP TABLE Championship;
DROP TABLE Coach;
DROP TABLE Sponsor;
DROP TABLE Match;
DROP TABLE Player;


