CREATE TABLE Player (
    PlayerID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PFName VARCHAR(30) NOT NULL,
    PLName VARCHAR(30) NOT NULL,   
    DOB DATE NOT NULL,
    Img VARCHAR(200) NOT NULL
);

CREATE TABLE Team (
	TeamName VARCHAR(40) NOT NULL PRIMARY KEY
);

CREATE TABLE Championship (
	ChampionshipName CHAR(40) NOT NULL PRIMARY KEY,
	ChampDate DATE NOT NULL
);

CREATE TABLE Coach (
	CoachID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	CoachFName VARCHAR(30) NOT NULL,
	CoachLName VARCHAR(30) NOT NULL,
	CoachDOB DATE NOT NULL
);

CREATE TABLE Match (
	MatchID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	MatchDate DATE,
	Location VARCHAR(30) NOT NULL,
	Result CHAR(5)
);

CREATE TABLE Sponsor (
	CompanyName VARCHAR(40) PRIMARY KEY
);

CREATE TABLE Player_Team_Contract(
    PlayerID INT NOT NULL, 
    TeamName VARCHAR(40), 
    PContr_Numb INT NOT NULL, 
    Start_Date DATE, 
    End_Date DATE,
    PRIMARY KEY(PlayerID,TeamName,PContr_Numb),
    FOREIGN KEY(PlayerID) REFERENCES Player(PlayerID) ON DELETE CASCADE,
    FOREIGN KEY(TeamName) REFERENCES Team(TeamName) ON DELETE CASCADE
);

CREATE TABLE Coach_Team_Contract(
    CoachID INT,
    TeamName VARCHAR(40) NOT NULL,
    CContr_Numb INT NOT NULL,
    Start_Date DATE, 
    End_Date DATE,
    PRIMARY KEY(CoachID,TeamName,CContr_Numb),
    FOREIGN KEY(CoachID) REFERENCES Coach(CoachID) ON DELETE CASCADE,
    FOREIGN KEY(TeamName) REFERENCES Team(TeamName) ON DELETE CASCADE
);

CREATE TABLE Player_PlaysRole_in_Match(
    PlayerID INT, 
    MatchID INT, 
    Role CHAR(2),
    PRIMARY KEY(PlayerID,MatchID),
    FOREIGN KEY(PlayerID) REFERENCES Player(PlayerID) ON DELETE CASCADE,
    FOREIGN KEY(MatchID) REFERENCES Match(MatchID) ON DELETE CASCADE
);

CREATE TABLE Player_Scores_in_Match (
    PlayerID INT, 
    MatchID INT, 
    Score INT,
    PRIMARY KEY(PlayerID,MatchID),
    FOREIGN KEY(PlayerID) REFERENCES Player(PlayerID) ON DELETE CASCADE,
    FOREIGN KEY(MatchID) REFERENCES Match(MatchID) ON DELETE CASCADE
);

CREATE TABLE Team_Wins_Championship (
    TeamName VARCHAR(40), 
    ChampionshipName CHAR(40), 
    Medal VARCHAR(6),
    PRIMARY KEY(TeamName,ChampionshipName),
    FOREIGN KEY(TeamName) REFERENCES Team(TeamName) ON DELETE CASCADE,
    FOREIGN KEY(ChampionshipName) REFERENCES Championship(ChampionshipName) ON DELETE CASCADE
);

CREATE TABLE Team_Participates_in_Match (
    TeamName VARCHAR(40),  
    MatchID INT, 
    PRIMARY KEY(TeamName,MatchID),
    FOREIGN KEY(TeamName) REFERENCES Team(TeamName) ON DELETE CASCADE,
    FOREIGN KEY(MatchID) REFERENCES Match(MatchID) ON DELETE CASCADE
);

CREATE TABLE Sponsor_Sponsors_Match (
    CompanyName VARCHAR(40),
    TeamName VARCHAR(40), 
    MatchID INT,
    PRIMARY KEY(CompanyName,TeamName,MatchID),
    FOREIGN KEY(CompanyName) REFERENCES Sponsor(CompanyName) ON DELETE CASCADE,
    FOREIGN KEY(TeamName) REFERENCES Team(TeamName) ON DELETE CASCADE,
    FOREIGN KEY(MatchID) REFERENCES Match(MatchID) ON DELETE CASCADE
)